---
version: '3.7'
services:
  nginx:
    image: daily/nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      cache_from:
        - daily/nginx
        - nginx:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost"]
      interval: 30s
      timeout: 3s
      retries: 10
    depends_on:
      - web
    ports:
      - 80:80
    restart: on-failure
    networks:
      - default
  mysql:
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=CHANGEME
      - MYSQL_DATABASE=daily
      - MYSQL_USER=daily_user
      - MYSQL_PASSWORD=CHANGEME
    restart: on-failure
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - default
    # ports:
    #   - 3306:3306
  base:
    image: daily/base
    build:
      context: .
      dockerfile: ./docker/base/Dockerfile
      cache_from:
        - daily/base
        - base:latest
  bootstrap:
    image: daily/bootstrap
    build:
      context: .
      dockerfile: ./docker/bootstrap/Dockerfile
      cache_from:
        - daily/bootstrap
        - bootstrap:latest
    depends_on:
      - base
      - mysql
    healthcheck:
      test: ["CMD", "exit", "1"]
    restart: on-failure
    networks:
      - default
  web:
    image: daily/web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      cache_from:
        - daily/web
        - web:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:5000"]
      interval: 30s
      timeout: 3s
      retries: 10
    restart: on-failure
    networks:
      - default

volumes:
  mysql:

networks:
  default:
